version: "3"
services:
  slack-next-gen-platform-example:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - ..:/project
    image: slack-next-gen-platform-example-image
    container_name: slack-next-gen-platform-example
    tty: true
    env_file: ../.env # shellスクリプト内でも環境変数として使用するため
